23AP_3: profile
antipatternmf/shades pull request #15
Opened 2023-03-12 05:39 UTC by nimura255

### Какую задачу решаем
 - добавил вёрстку для ProtectedLayout;
 - изменил логику восстановления сессии и проверки авторизации для защищённых рутов (пришлось);
 - реализовал страницу профиля.

2023-03-12 12:01 UTC, aromanovnik approved these changes

2023-03-13 06:10 UTC, EzhikTT commented on packages/client/src/api/chat/api/users-api.ts
> +      const localVarAxiosArgs = await localVarAxiosParamCreator
жОское название)))

2023-03-13 06:17 UTC, EzhikTT commented on packages/client/src/pages/Profile/EditInfoForm/index.tsx
> +  return (
Можно начать компонент(фрагмент) на строчке с ретурном и не нужны круглые скобки

2023-03-13 06:18 UTC, EzhikTT requested changes

2023-03-13 06:18 UTC, EzhikTT commented on packages/client/src/pages/Profile/AvatarUploader/index.tsx
> +  const avatarSrc = useAppSelector((state) => state.user.data?.avatar) || '';
Пустое значение лучше добавить в функцию селектора

2023-03-13 06:18 UTC, EzhikTT commented on packages/client/src/components/ProtectedLayout/index.tsx
> +  const prevPagePathname = getPathnameOfPrevPage();
А у роутера нет методов в хуке для этого?

2023-03-13 07:29 UTC, nimura255 commented on packages/client/src/api/chat/api/users-api.ts
> +      const localVarAxiosArgs = await localVarAxiosParamCreator
🤷‍♂️
Не я придумывал, возможно оно вообще сгенерировано

2023-03-13 07:29 UTC, nimura255 commented on packages/client/src/pages/Profile/EditInfoForm/index.tsx
> +  return (
Преттиер автоматом делает такое форматирование

2023-03-13 07:30 UTC, nimura255 commented on packages/client/src/pages/Profile/AvatarUploader/index.tsx
> +  const avatarSrc = useAppSelector((state) => state.user.data?.avatar) || '';
Почему?

2023-03-13 07:33 UTC, nimura255 commented on packages/client/src/components/ProtectedLayout/index.tsx
> +  const prevPagePathname = getPathnameOfPrevPage();
Это функция не для получения предыдущей страницы в истории, а в навигационной структуре приложения
`/profile` -> `/`
`/forum/topic` -> `/forum`

2023-03-14 07:33 UTC, indiagolph99 approved these changes

2023-03-14 13:47 UTC, EzhikTT commented on packages/client/src/pages/Profile/AvatarUploader/index.tsx
> +  const avatarSrc = useAppSelector((state) => state.user.data?.avatar) || '';
Более читаемо, и, если что-то пойдет не так с хуками редакса, мы увидим сразу ошибку, которая будет при вызове, а не просто пустое значение и поиск ошибки неизвестно где

2023-03-14 13:47 UTC, EzhikTT approved these changes
Все ок

2023-03-14 13:49 UTC, nimura255 commented on packages/client/src/pages/Profile/AvatarUploader/index.tsx
> +  const avatarSrc = useAppSelector((state) => state.user.data?.avatar) || '';
На случай таких ошибок баундари делать нужно же, не?)

2023-03-14 17:25 UTC, ghost approved these changes

2023-03-14 21:07 UTC, merged