POC game level & engine
antipatternmf/shades pull request #17
Opened 2023-03-16 16:11 UTC by indiagolph99

2023-03-16 16:37 UTC, aromanovnik submitted a review, later dismissed

2023-03-16 16:39 UTC, magomedaliev submitted a review, later dismissed

2023-03-16 20:11 UTC, SergeyichNik approved these changes, later dismissed

2023-03-17 11:18 UTC, EzhikTT commented on packages/client/src/core/Canvas.tsx
> +              obstacles.some((it) =>
А почему не одну строчку? У вас ограничение на 80 символов?

2023-03-17 11:20 UTC, EzhikTT commented on packages/client/src/core/CanvasObstacles.tsx
> +    drawables.forEach((drawable) => {
А почему здесь `foreach()', а не нормальный цикл `for..of`? сейчас не 2007=))

2023-03-17 11:23 UTC, EzhikTT requested changes

2023-03-17 11:23 UTC, EzhikTT commented on packages/client/src/core/CanvasObstacles.tsx
> +  }, [props, ctx, ref]);
А тут не происходит зацикливания? Ты меняешь `ctx` в подписке на его изменение

2023-03-18 09:31 UTC, indiagolph99 commented on packages/client/src/core/CanvasObstacles.tsx
> +    drawables.forEach((drawable) => {
честно, не придал значения большого. во всех остальных местах работаем через методы массивов

2023-03-18 09:32 UTC, indiagolph99 commented on packages/client/src/core/CanvasObstacles.tsx
> +  }, [props, ctx, ref]);
на удивление, все нормально. а вот ref был лишний, из-за него несколько лишних эффектов отрабатывало

2023-03-18 09:32 UTC, indiagolph99 commented on packages/client/src/core/Canvas.tsx
> +              obstacles.some((it) =>
поправил

2023-03-18 11:08 UTC, nimura255 commented on packages/client/src/core/CanvasObstacles.tsx
> +    drawables.forEach((drawable) => {
Airbnb конфиг настаивает на использовании `forEach()` вместо `for ... of`

2023-03-18 13:07 UTC, nimura255 approved these changes

2023-03-18 13:08 UTC, aromanovnik approved these changes

2023-03-18 15:59 UTC, magomedaliev approved these changes

2023-03-20 10:44 UTC, indiagolph99 commented
@EzhikTT, review please

2023-03-20 12:58 UTC, EzhikTT commented on packages/client/src/core/CanvasObstacles.tsx
> +    drawables.forEach((drawable) => {
Очень странно, тк он намного хуже и медленней

2023-03-20 12:58 UTC, EzhikTT approved these changes
Все ок

2023-03-20 13:09 UTC, merged