23AP-42: tools setup and configuration
antipatternmf/shades pull request #2
Opened 2023-02-24 14:19 UTC by nimura255

- Настроил eslint, сделал разные конфиги для клиента и сервера; для клиента используется airbnb конфиг; не стал выносить общие параметры в корневой конфиг, потому что IDE не мержит параметры при линтинге.
 - Настроил prettier и styleling (styleling только для клиента).
 - Проверил запуск, сборку и работу pre-commit хука.
 - Поставил postcss, postcss-modules и postcss-nested.
 - Поставил classnames.
 - Поддержка CSS Modules уже есть в vite; для этого названия файлов со стилями должны быть вида *.modules.pcss (см. packages/client/App.modules.pcss).
 - jest и @testing-library/react уже стояли в проекте, пришлось только замокать .pcss файлы для джеста.

2023-02-24 14:21 UTC, indiagolph99 approved these changes

2023-02-24 14:27 UTC, magomedaliev approved these changes

2023-02-24 14:43 UTC, aromanovnik approved these changes

2023-02-24 15:01 UTC, SergeyichNik approved these changes

2023-02-26 08:32 UTC, EzhikTT requested changes
Ответьте на вопросы) 
+ добавляйте меня, пожалуйста, в список апрувольщиков
+ лок файл не обязателен в гите, тк он генерируемый, а каких-то жестких версий пакетов вам не нужно

2023-02-26 08:32 UTC, EzhikTT commented on packages/client/jest.config.js
> +    SERVER_PORT: process.env.SERVER_PORT,
Чем не понравилось прошлое название? Константы в `node.js` принято записывать, начиная с __

2023-02-26 08:32 UTC, EzhikTT commented on package.json
> +    "@evilmartians/lefthook": "1.1.1",
Зачем убирать крышечку?

2023-02-26 10:24 UTC, nimura255 commented on package.json
> +    "@evilmartians/lefthook": "1.1.1",
Думал, что с прошлого модуля осталось соглашение фиксировать версии зависимостей

2023-02-26 10:25 UTC, nimura255 commented on packages/client/jest.config.js
> +    SERVER_PORT: process.env.SERVER_PORT,
Линтеру с airbnb конфигом не нравятся такие названия

2023-02-26 10:45 UTC, nimura255 commented on package.json
> +    "@evilmartians/lefthook": "1.1.1",
И думаю, что лучше лок файл оставить в репозитории, чтобы у всех +- одни и те же node_modules были

2023-02-28 09:34 UTC, EzhikTT approved these changes
Все ок

2023-02-28 09:37 UTC, merged