23 ap 24 leaderboard
antipatternmf/shades pull request #20
Opened 2023-03-22 11:23 UTC by aromanovnik

Сверстал список лидеров;
Создал компонент пагинации (Пригодится для списков форума и т.д.)
Сделал шапку. 
ps. Сливать буду только после презентации, чтобы не поломать main 

<img width="804" alt="Снимок экрана 2023-03-22 в 14 21 00" src="https://user-images.githubusercontent.com/85519284/226889694-eb5bd601-558f-48ab-ad6b-fd2b54fb9eaa.png">

2023-03-23 07:51 UTC, EzhikTT commented on packages/client/src/components/Header/index.tsx
> +        {isShowBackButton ? (
Можно записать через `&&` - `{isShowBackButton  && <SomeComponent/>}`

2023-03-23 07:53 UTC, EzhikTT commented on packages/client/src/pages/LeaderBoard/index.tsx
> +// ONLY FOR DEMO (START)
`TODO` еще бы добавлять. Это умеет находить и выделять `ide`

2023-03-23 07:53 UTC, EzhikTT requested changes

2023-03-23 07:53 UTC, EzhikTT commented on packages/client/src/components/ProtectedLayout/index.tsx
> +// function getPathnameOfPrevPage() {
Зачем комментировать, если оно под гитом?

2023-03-23 15:31 UTC, indiagolph99 approved these changes

2023-03-24 10:29 UTC, nimura255 approved these changes

2023-03-24 10:33 UTC, magomedaliev approved these changes

2023-03-24 14:31 UTC, SergeyichNik approved these changes

2023-03-25 20:26 UTC, merged

2023-03-27 17:25 UTC, EzhikTT reviewed
Все ок