23AP-38/23AP-39
antipatternmf/shades pull request #25
Opened 2023-04-06 19:15 UTC by SergeyichNik

### Какую задачу решаем
Настроил рендер jsx компонент, подружил redux и SSR

2023-04-06 20:23 UTC, aromanovnik submitted a review, later dismissed

2023-04-07 10:14 UTC, magomedaliev submitted a review, later dismissed

2023-04-07 10:28 UTC, indiagolph99 submitted a review, later dismissed

2023-04-08 05:49 UTC, SergeyichNik commented
@EzhikTT Нужно ревью

2023-04-09 14:34 UTC, EzhikTT requested changes

2023-04-09 14:34 UTC, EzhikTT commented on packages/client/src/router/index.tsx
> +import MainPage from 'pages/Main';
А почему `lazy` заменили?

2023-04-10 08:08 UTC, SergeyichNik commented on packages/client/src/router/index.tsx
> +import MainPage from 'pages/Main';
Из за асинхронного импорта, с ssr немного сложней работа выходит поэтому пока убрал

2023-04-11 08:19 UTC, nimura255 submitted a review, later dismissed

2023-04-11 11:39 UTC, magomedaliev approved these changes, later dismissed

2023-04-11 11:55 UTC, nimura255 submitted a review, later dismissed

2023-04-11 14:52 UTC, EzhikTT approved these changes, later dismissed
Все ок

2023-04-11 19:41 UTC, indiagolph99 submitted a review, later dismissed

2023-04-11 21:23 UTC, indiagolph99 approved these changes

2023-04-11 21:36 UTC, nimura255 approved these changes

2023-04-11 22:18 UTC, aromanovnik approved these changes

2023-04-12 10:39 UTC, magomedaliev approved these changes

2023-04-12 11:07 UTC, merged