23AP-11/23AP-55
antipatternmf/shades pull request #3
Opened 2023-02-26 19:55 UTC by SergeyichNik

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-27 09:16 UTC, aromanovnik approved these changes, later dismissed

2023-02-28 07:58 UTC, indiagolph99 approved these changes, later dismissed

2023-02-28 09:39 UTC, nimura255 commented on packages/client/src/store/hooks.ts
> +export const useAppDispatch: () => AppDispatch = useDispatch;
А почему не через дженерик?
`export const useAppDispatch = useDispatch<AppDispatch>;`

2023-02-28 09:39 UTC, nimura255 commented on packages/client/src/components/AuthLayout/index.tsx
> +  }, [isAuth, navigate, dispatch]);
Вот здесь dispatch лишний в массиве зависимостей
Странно, что линтер не подсветил это

2023-02-28 09:39 UTC, nimura255 commented on packages/client/src/reducers/user/index.ts
> +export { sliceName, setUserIsAuth, default as userReducer } from './reducer';
Мб стоит редьюсеры хранить рядом со стором?

2023-02-28 09:42 UTC, SergeyichNik commented on packages/client/src/components/AuthLayout/index.tsx
> +  }, [isAuth, navigate, dispatch]);
как раз из за линтера он там и оказался

2023-02-28 09:46 UTC, EzhikTT requested changes

2023-02-28 09:46 UTC, EzhikTT commented on packages/client/src/hocs/withRedux.tsx
> +export const withRedux = (component: () => React.ReactNode) => function () {
HOC'и тоже должны называться с большой буквы

2023-02-28 09:46 UTC, EzhikTT commented on packages/client/src/components/AuthLayout/index.tsx
> +  }, [isAuth, navigate, dispatch]);
+1

2023-02-28 09:46 UTC, EzhikTT commented on packages/client/src/app/App.tsx
> +import { PathTo } from '../constants';
Почему такое странное название для константы? Тут не нужно `to`, если вы хотите пути объединить в один объект, а назвать его было бы правильно - `PATHS`

2023-02-28 09:46 UTC, EzhikTT commented on packages/client/src/app/App.tsx
> +import { lazy } from 'react';
Почему у файла название не `index`?

2023-02-28 09:46 UTC, EzhikTT commented on packages/client/package.json
> +    "@reduxjs/toolkit": "^1.9.3",
Почему где-то остались крышечки, а где-то нет?

2023-02-28 11:33 UTC, magomedaliev approved these changes, later dismissed

2023-02-28 11:45 UTC, SergeyichNik commented on packages/client/src/store/hooks.ts
> +export const useAppDispatch: () => AppDispatch = useDispatch;
В документации показан именно такой вариант

2023-02-28 11:45 UTC, SergeyichNik commented on packages/client/src/reducers/user/index.ts
> +export { sliceName, setUserIsAuth, default as userReducer } from './reducer';
мы как бы за структуру не договаривались, поэтому я не стал пока запариваться.Сделал структуру в одну линию так сказать

2023-02-28 11:45 UTC, SergeyichNik commented on packages/client/src/app/App.tsx
> +import { PathTo } from '../constants';
Мы на работе для множества констант (объект, массив) используем запись PascalCase, а внутри множества и для одиночных констант UPPERCASE. Так что это привычка

2023-02-28 11:45 UTC, SergeyichNik commented on packages/client/src/hocs/withRedux.tsx
> +export const withRedux = (component: () => React.ReactNode) => function () {
![image](https://user-images.githubusercontent.com/85055618/221819324-b4596db3-5626-4bcb-a636-af3c10aad3dc.png)
документация React

2023-02-28 11:45 UTC, SergeyichNik commented on packages/client/src/components/AuthLayout/index.tsx
> +  }, [isAuth, navigate, dispatch]);
Всё, понял в чём косяк, исправил

2023-02-28 18:03 UTC, nimura255 approved these changes, later dismissed

2023-02-28 19:17 UTC, indiagolph99 commented on packages/client/src/app/App.tsx
> +import { PathTo } from '../constants';
соглашусь с ревьюром, давайте делать систайл константы

2023-03-01 07:52 UTC, SergeyichNik commented on packages/client/src/app/App.tsx
> +import { PathTo } from '../constants';
Систайл константы? Дай ссылку где об этом почитать

2023-03-01 08:04 UTC, nimura255 approved these changes

2023-03-01 08:14 UTC, aromanovnik approved these changes

2023-03-01 08:33 UTC, indiagolph99 commented on packages/client/src/app/App.tsx
> +import { PathTo } from '../constants';
https://www.doc.ic.ac.uk/lab/cplus/cstyle.html#N10441

2023-03-01 08:45 UTC, indiagolph99 approved these changes

2023-03-01 13:17 UTC, magomedaliev approved these changes

2023-03-01 13:25 UTC, EzhikTT approved these changes
Все ок

2023-03-01 13:44 UTC, merged