23AP-20; 23AP-20;
antipatternmf/shades pull request #4
Opened 2023-02-26 20:43 UTC by aromanovnik

Сгенерировал API запросы и типы;
Добавил axios на клиент;

2023-02-27 09:17 UTC, indiagolph99 commented on packages/client/src/api/chat/base.ts
> + */
jsdoc комментарии обязательны?

2023-02-27 09:26 UTC, SergeyichNik approved these changes, later dismissed

2023-02-27 10:06 UTC, aromanovnik commented on packages/client/src/api/chat/base.ts
> + */
Его не убрать, если только руками =( 
Все доступные параметры: https://openapi-generator.tech/docs/generators/typescript-axios/

2023-02-28 07:58 UTC, indiagolph99 submitted a review, later dismissed

2023-02-28 09:49 UTC, EzhikTT requested changes
Слишком много игноров и странных функций, которые должны быть классами. Без этих правок нет смысла смотреть все сразу

2023-02-28 09:49 UTC, EzhikTT commented on packages/client/src/api/chat/api/charts-api.ts
> +export const ChartsApiFp = function (configuration?: Configuration) {
Почему не классы?

2023-02-28 09:49 UTC, EzhikTT commented on packages/client/src/api/chat/api/charts-api.ts
> +// @ts-ignore
Зачем оно тут?

2023-02-28 10:39 UTC, aromanovnik commented on packages/client/src/api/chat/api/charts-api.ts
> +export const ChartsApiFp = function (configuration?: Configuration) {
api и типа сгенерированы автоматически из swagger.json с помощью библиотеки openapi-generator , на что нам дали добро. Это писалось не руками, и трогать это не нужно.

2023-02-28 10:40 UTC, aromanovnik commented on packages/client/src/api/chat/api/charts-api.ts
> +// @ts-ignore
Вы про axios или про chat-api? 
1) axios мы будем использовать для запросов
2) см. ответ выше.

2023-02-28 11:29 UTC, magomedaliev approved these changes, later dismissed

2023-02-28 18:04 UTC, nimura255 requested changes
Подтяни изменения из main

2023-03-01 13:25 UTC, EzhikTT commented on packages/client/src/api/chat/api/charts-api.ts
> +export const ChartsApiFp = function (configuration?: Configuration) {
Оки

2023-03-01 13:26 UTC, EzhikTT commented on packages/client/src/api/chat/api/charts-api.ts
> +// @ts-ignore
Про ts-ignore. Их слишком много

2023-03-01 13:27 UTC, EzhikTT requested changes
Не могу принять ПР с таким количеством игноров

2023-03-01 13:27 UTC, EzhikTT commented on packages/client/src/api/chat/api.ts
> +/* eslint-disable */
А почему отключили?))))

2023-03-01 14:43 UTC, aromanovnik commented on packages/client/src/api/chat/api.ts
> +/* eslint-disable */
Это не руками отключается, а автоматически билдится. Если вы не знакомы с swagger или как билдятся api and types автоматически: https://swagger.io/ , https://openapi-generator.tech/ 
Вообще по правильному изначально создается  swagger.yaml (Если RESTful APIs) бэкэндерами при согласовании с фронтендерами, на клиенте автоматически билдятся api и НИКОГДА руками это не трогается, это делается для того, что если на сервере изменили тип или добавили ручки или еще что то, то на клиенте достаточно перебилдить api и изменить только в ОДНОМ месте  модель. 

Лучше познакомиться можно -> https://www.youtube.com/watch?v=lYjm2w8-ERI

НО специально по вашему желанию удалил лишние API, типы и tslint:disable & eslint-disable

2023-03-01 14:52 UTC, indiagolph99 approved these changes

2023-03-01 14:52 UTC, nimura255 approved these changes

2023-03-01 20:08 UTC, magomedaliev approved these changes

2023-03-02 06:08 UTC, SergeyichNik approved these changes

2023-03-02 12:45 UTC, EzhikTT approved these changes
Про генерацию ок, понял все. Прикладывайте сразу на такие спорные места ответы наставника и что за либу юзаете

2023-03-02 12:53 UTC, merged