Basic classes for game entities + drawing mechanism
antipatternmf/shades pull request #7
Opened 2023-03-03 09:05 UTC by indiagolph99

2023-03-03 09:20 UTC, SergeyichNik approved these changes, later dismissed

2023-03-04 08:25 UTC, EzhikTT requested changes
Напоминаю, что меня нужно добавлять ко всем ПРам

2023-03-04 08:25 UTC, EzhikTT commented on packages/client/src/core/CanvasLine.ts
> +    if (context) {
А почему бы не вынести `context` в свойства класса?

2023-03-04 12:52 UTC, aromanovnik approved these changes

2023-03-04 18:55 UTC, indiagolph99 commented on packages/client/src/core/CanvasLine.ts
> +    if (context) {
компонент с канвасом получает на вход уже готовые инстансы фигур. иначе надо будет сначала инстанциировать канвас слой и только потом уже фигуры и потом уже их рисовать

2023-03-05 10:24 UTC, SergeyichNik approved these changes

2023-03-05 11:05 UTC, magomedaliev approved these changes

2023-03-06 12:36 UTC, nimura255 approved these changes

2023-03-07 11:30 UTC, EzhikTT approved these changes
Все ок

2023-03-07 12:29 UTC, merged