23AP-16 / 23AP-2 / 23AP-15
antipatternmf/shades pull request #9
Opened 2023-03-05 09:19 UTC by SergeyichNik

- Добавлены страницы Авторизации и Регистрации
- Добавлены сервисы авторизации, регистрации, получения данных, выход из приложения 
- Добавлены пакеты react-hook-form (работа с формами) и yup (валидация)

2023-03-05 11:05 UTC, magomedaliev approved these changes, later dismissed

2023-03-05 19:18 UTC, nimura255 commented on packages/client/src/pages/SignUp/index.tsx
> +              register={register}
Вижу, что здесь TS ругается на register
Предлагаю сделать инпут немного по-другому
Не прокидывать в пропсах не саму функцию register, а то, что она возвращает.
return компонента SignIn:
```jsx
<div className={cx('container')}>
  <h2>SignIn</h2>
  <form onSubmit={handleSubmit(onSubmitHandle)}>
    {signInFields.map(({ name, type }) => {
      return (
        <InputTmp
          key={name}
          {...register(name)}
          error={errors[name]?.message}
          type={type}
        />
      );
    })}
    <input type="submit" />
  </form>
  <Link
    to="/sign-up"
    state={{ from: location }}
  >
    No account yet? Sign up
  </Link>
</div>
```
Компонент InputTemp:
```tsx
interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  error?: string;
}

const cx = classNames.bind(styles);

const InputTmp = forwardRef<HTMLInputElement, InputProps>(
  ({ error, ...props }: InputProps, ref) => {
    return (
      <div className={cx('container')}>
        <input
          {...props}
          ref={ref}
        />
        {error && <span style={{ color: 'red' }}>{error}</span>}
      </div>
    );
  },
);
```
Плюс у нас тогда будет инпут, который не зависит от схем форм и может быть использован везде.

2023-03-05 19:24 UTC, nimura255 commented on packages/client/src/pages/Main/index.tsx
> +    if (!userInfo && !withoutRequest.includes(location.state?.from.pathname)) {
Кажется, что это нужно вынести в App, потому что сейчас этот эффект срабатывает только на корневой странице и в этой проверке pathname нет смысла.
\+ почему здесь идет проверка location.state?.from.pathname, а не location.pathname

2023-03-05 19:26 UTC, nimura255 commented on packages/client/jest.config.js
> +  "^api(.*)$": "<rootDir>/src/api",
Предлагаю добавить какой-нибудь символ вначале алиасов, чтобы было понятно, что это наши алиасы
Например $:
```js
import Input from '$components/Input';
```

2023-03-05 19:30 UTC, nimura255 commented on packages/client/src/app/index.tsx
> +      <Route element={<PublicLayout />}>
Немного доматаюсь до нейминга:
В этом компоненте используется AuthLayout для рутов, которые требуют авторизации.
Но название AuthLayout выглядит так, как будто это layout для страниц авторизации.
Понимаю, что надо было раньше до этого доматываться, но всё же.
Мб нам стоит как-то переименовать PublicLayout и AuthLayout, чтобы не было путаницы?

2023-03-05 19:33 UTC, nimura255 commented on packages/client/src/components/InputTmp/index.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
Предлагаю заменить на это:
```tsx
interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  error?: string;
}

const cx = classNames.bind(styles);

const InputTmp = forwardRef<HTMLInputElement, InputProps>(
  ({ error, ...props }: InputProps, ref) => {
    return (
      <div className={cx('container')}>
        <input
          {...props}
          ref={ref}
        />
        {error && <span style={{ color: 'red' }}>{error}</span>}
      </div>
    );
  },
);
```
Тогда не придётся думать о типизации проперти register.

2023-03-05 19:35 UTC, nimura255 commented on packages/client/src/components/PublicLayout/index.tsx
> +    if (!userInfo && !withoutRequest.includes(location.state?.from.pathname)) {
Мб стоит такие проверки вынести повыше (например, в App)?

2023-03-05 19:38 UTC, nimura255 commented on packages/client/src/types/common.d.ts
> +  type Status = 'fulfilled' | 'pending' | 'rejected' | null;
Мне кажется, что такое не стоит выносить в common, потому что это специфично для запросов.

2023-03-05 19:39 UTC, nimura255 commented on packages/client/tsconfig.json
> +      "api/*": ["api/*"],
Предлагаю добавить какой-нибудь символ вначале алиасов, чтобы было понятно, что это наши алиасы
Например $:
```js
import Input from '$components/Input';
```

2023-03-05 19:40 UTC, nimura255 requested changes
Нужно поправить тайпскриптовую ошибку и прогнать преттиер

2023-03-05 19:51 UTC, nimura255 requested changes
Нужно поправить тайпскриптовую ошибку и прогнать преттиер

2023-03-05 19:51 UTC, nimura255 commented on packages/client/src/pages/SignUp/index.tsx
> +              register={register}
Вижу, что здесь TS ругается на register
Предлагаю сделать инпут немного по-другому
Не прокидывать в пропсах не саму функцию register, а то, что она возвращает.
return компонента SignIn:
```jsx
<div className={cx('container')}>
  <h2>SignIn</h2>
  <form onSubmit={handleSubmit(onSubmitHandle)}>
    {signInFields.map(({ name, type }) => {
      return (
        <InputTmp
          key={name}
          {...register(name)}
          error={errors[name]?.message}
          type={type}
        />
      );
    })}
    <input type="submit" />
  </form>
  <Link
    to="/sign-up"
    state={{ from: location }}
  >
    No account yet? Sign up
  </Link>
</div>
```
Компонент InputTemp:
```tsx
interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  error?: string;
}

const cx = classNames.bind(styles);

const InputTmp = forwardRef<HTMLInputElement, InputProps>(
  ({ error, ...props }: InputProps, ref) => {
    return (
      <div className={cx('container')}>
        <input
          {...props}
          ref={ref}
        />
        {error && <span style={{ color: 'red' }}>{error}</span>}
      </div>
    );
  },
);
```
Плюс у нас тогда будет инпут, который не зависит от схем форм и может быть использован везде.

2023-03-05 19:51 UTC, nimura255 commented on packages/client/src/pages/Main/index.tsx
> +    if (!userInfo && !withoutRequest.includes(location.state?.from.pathname)) {
Кажется, что это нужно вынести в App, потому что сейчас этот эффект срабатывает только на корневой странице и в этой проверке pathname нет смысла.
\+ почему здесь идет проверка location.state?.from.pathname, а не location.pathname?

2023-03-05 19:51 UTC, nimura255 commented on packages/client/src/app/index.tsx
> +      <Route element={<PublicLayout />}>
Немного домотаюсь до нейминга)
В этом компоненте используется AuthLayout для рутов, которые требуют авторизации.
Но название AuthLayout выглядит так, как будто это layout для страниц авторизации.
Понимаю, что надо было раньше до этого доматываться, но всё же.
Мб нам стоит как-то переименовать PublicLayout и AuthLayout, чтобы не было путаницы?
Например, можно оставить название PublicLayout, а AuthLayout заменить на ProtectedLayout.

2023-03-05 19:51 UTC, nimura255 commented on packages/client/src/components/InputTmp/index.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
Предлагаю заменить на это:
```tsx
interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  error?: string;
}

const cx = classNames.bind(styles);

const InputTmp = forwardRef<HTMLInputElement, InputProps>(
  ({ error, ...props }: InputProps, ref) => {
    return (
      <div className={cx('container')}>
        <input
          {...props}
          ref={ref}
        />
        {error && <span style={{ color: 'red' }}>{error}</span>}
      </div>
    );
  },
);
```
Тогда не придётся думать о типизации проперти register и мы сможем использовать этот инпут везде, хоть с другими схемами, хоть вообще вне форм.

2023-03-05 19:51 UTC, nimura255 commented on packages/client/src/components/PublicLayout/index.tsx
> +    if (!userInfo && !withoutRequest.includes(location.state?.from.pathname)) {
Мб стоит такие проверки вынести повыше (например, в App)?
Тогда не придётся повторять одно и тоже в разных обёртках.

2023-03-05 19:51 UTC, nimura255 commented on packages/client/src/types/common.d.ts
> +  type Status = 'fulfilled' | 'pending' | 'rejected' | null;
Мне кажется, что такое не стоит выносить в common, потому что это специфично для запросов (если этот статус запроса к API).

2023-03-05 19:51 UTC, nimura255 commented on packages/client/tsconfig.json
> +      "api/*": ["api/*"],
Предлагаю добавить какой-нибудь символ вначале алиасов, чтобы было понятно, что это наши алиасы
Например $:
```js
import Input from '$components/Input';
```

2023-03-05 20:01 UTC, nimura255 commented on packages/client/src/components/InputTmp/index.tsx
> +import React, { HTMLInputTypeAttribute, InputHTMLAttributes } from 'react';
Кстати, зачем во всех файлах компонент делается импорт React?
Начиная с 17-й версии этого делать больше не нужно.

2023-03-05 22:33 UTC, indiagolph99 requested changes

2023-03-05 22:33 UTC, indiagolph99 commented on packages/client/.eslintignore
> +src/api
очень жёстко, надо убрать

2023-03-05 22:33 UTC, indiagolph99 commented on packages/client/.eslintrc.cjs
> +    "react/require-default-props": "off",
вроде как договорились на одинарные кавычки, где не предпочитается иначе

2023-03-05 22:33 UTC, indiagolph99 commented on packages/client/package.json
> +    "react-hook-form": "^7.43.3",
договаривались на фиксированные зависимости

2023-03-05 22:33 UTC, indiagolph99 commented on packages/client/src/app/index.tsx
> +      <Route element={<PublicLayout />}>
а можно вообще сделать так, чтобы страницы, отображение которых зависит от сессии, не оборачивались в специальные компоненты? можно как-нибудь в роутер прокидывать мета-информацию о сессии(например, юзер из стора) и в зависимости от его наличия/отсутствия роутер будет делать редирект?

2023-03-05 22:35 UTC, indiagolph99 commented
предлагаю сквошить коммиты + делать аменд перед пушем, все равно в реквесте дифф от всех коммитов смотрится, а так история чище будет

2023-03-06 07:02 UTC, aromanovnik approved these changes, later dismissed

2023-03-06 17:45 UTC, SergeyichNik commented on packages/client/tsconfig.json
> +      "api/*": ["api/*"],
а всё уже, надо было раньше

2023-03-06 18:43 UTC, nimura255 requested changes

2023-03-06 18:43 UTC, nimura255 commented on packages/client/src/pages/SignIn/index.tsx
> +              register={register}
Тут TS ругается, в предыдущих комментах предложил немного переделать компонент, чтобы исправить ошибку + улучить переиспользуемость компонента
<img width="953" alt="Screenshot 2023-03-06 at 22 41 18" src="https://user-images.githubusercontent.com/44906325/223201564-c4b8a37e-7234-4e7d-9849-5a178122ee8e.png">

2023-03-06 18:46 UTC, nimura255 commented on packages/client/tsconfig.json
> +      "api/*": ["api/*"],
Почему надо было раньше?
Так-то алиасы ты в этом реквесте добавляешь

2023-03-07 05:47 UTC, indiagolph99 commented on packages/client/tsconfig.json
> +      "api/*": ["api/*"],
согл, не вижу препятствий для аменда

2023-03-07 11:36 UTC, EzhikTT approved these changes, later dismissed
Все ок

2023-03-07 14:45 UTC, indiagolph99 requested changes

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/pages/Main/style.module.pcss
> +    padding:20px 0;
стиль: пробел после двоеточия

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/app/index.tsx
> +import { Router } from '../router/Router';
можно алиас вместо относительного пути?

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/components/InputTmp/index.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
Если был сделан ребейз после реквеста Леонида, то надо убрать этот файл и использовать наши компоненты

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/constants/schema.ts
> +import { SignUpRequest } from 'api/chat';
название файла - схема чего? если не является требованием пакета, который используется для валидации, можно ли сделать что-то вроде `userFormValidationSchema`?

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/pages/SignIn/config/config.ts
> +import { Fields, schema } from 'constants/schema';
тоже название: какой конфиг, для чего конфиг?

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/pages/SignIn/index.tsx
> +      <form onSubmit={handleSubmit(onSubmitHandle)}>
SignUp и SignIn по шаблону и апи очень похожи. можно сделать дженерик компонент

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/pages/SignUp/index.tsx
> +    try {
зачем `async` функции оборачивать в `try`?

2023-03-07 14:45 UTC, indiagolph99 commented on packages/client/src/reducers/user/thunks.ts
> +export const userGet = createAsyncThunk(`${sliceName}/userGet`, async (data, thunkAPI) => {
```js
return authApi.authUserGet()
  .then((res) => thunkAPI.fulfillWithValue(res.data)
  .catch((e) => thunkAPI.rejectWithValue(requestErrorHandler(e))
  ```

2023-03-07 15:01 UTC, aromanovnik approved these changes

2023-03-07 16:42 UTC, ghost approved these changes

2023-03-07 17:32 UTC, magomedaliev approved these changes

2023-03-07 18:10 UTC, indiagolph99 approved these changes

2023-03-07 18:12 UTC, nimura255 approved these changes

2023-03-07 18:15 UTC, merged